Letest Modified file

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,74 +1,93 @@
+// pipeline{
+//     agent any
+//     environment {
+//         IMAGE_NAME = "ajaydhadi95/frontend"
+//         IMAGE_TAG = "${BUILD_NUMBER}"
+//         APP_SERVER = "15.206.149.108"
+//     }
+//     stages {
+//         stage('checkout') {
+//             steps {
+//                 git branch: 'main',
+//                 url: 'https://github.com/ajaydhadi95-gif/Jenkins-webapp.git'
+//             }
+//         }
+//         stage('build Docker image'){
+//             steps {
+//                 sh '''
+//                 docker build  -f docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
+//                 '''
+//             }
+//         }
+//         stage('Docker Login') {
+//             steps {
+//                 withCredentials([
+//                     usernamePassword(
+//                         credentialsId:'DockerCred',
+//                         usernameVariable:'DOCKER_USER',
+//                         passwordVariable:'DOCKER_PASS',
+//                     )
+//                 ]) {
+//                     sh'''
+//                     echo $DOCKER_PASS | docker login \
+//                     -u $DOCKER_USER \
+//                     --password-stdin
+//                     '''
+//                 }
+//             }
+//         }
+//         stage('push Image') {
+//             steps {
+//                 sh '''
+//                 docker push $IMAGE_NAME:$IMAGE_TAG
+//                 docker tag \
+//                 $IMAGE_NAME:$IMAGE_TAG \
+//                 $IMAGE_NAME:latest 
+//                 docker push $IMAGE_NAME:latest
+//                 '''
+//             }
+//         }
+//         stage('Deploy to App Server') {
+//             steps {
+//                 sh """
+//                 ssh ubuntu@$APP_SERVER '
+//                 docker pull $IMAGE_NAME:latest
+//                 docker stop frontend || true
+//                 docker rm frontend || true
+//                 docker run -d \
+//                 --name frontend \
+//                 -p 80:80 \
+//                 $IMAGE_NAME:latest
+//                 '
+//                 """
+//             }
+//         }
+//     }
+//     post {
+//         success {
+//             echo "Deployment successful"
+//         }
+//         failure {
+//             echo "Deployment failed"
+//         }
+//     }
+// }
+
+
 pipeline{
     agent any
-    environment {
-        IMAGE_NAME = "ajaydhadi95/frontend"
-        IMAGE_TAG = "${BUILD_NUMBER}"
-        APP_SERVER = "15.206.149.108"
-    }
-    stages {
-        stage('checkout') {
-            steps {
-                git branch: 'main',
-                url: 'https://github.com/ajaydhadi95-gif/Jenkins-webapp.git'
-            }
-        }
-        stage('build Docker image'){
-            steps {
-                sh '''
-                docker build  -f docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
-                '''
-            }
-        }
-        stage('Docker Login') {
-            steps {
-                withCredentials([
-                    usernamePassword(
-                        credentialsId:'DockerCred',
-                        usernameVariable:'DOCKER_USER',
-                        passwordVariable:'DOCKER_PASS',
-                    )
-                ]) {
-                    sh'''
-                    echo $DOCKER_PASS | docker login \
-                    -u $DOCKER_USER \
-                    --password-stdin
-                    '''
-                }
-            }
-        }
-        stage('push Image') {
-            steps {
-                sh '''
-                docker push $IMAGE_NAME:$IMAGE_TAG
-                docker tag \
-                $IMAGE_NAME:$IMAGE_TAG \
-                $IMAGE_NAME:latest 
-                docker push $IMAGE_NAME:latest
-                '''
-            }
-        }
-        stage('Deploy to App Server') {
-            steps {
+    stages{
+        stage('Deployment'){
+            steps{
                 sh """
-                ssh ubuntu@$APP_SERVER '
-                docker pull $IMAGE_NAME:latest
-                docker stop frontend || true
-                docker rm frontend || true
-                docker run -d \
-                --name frontend \
-                -p 80:80 \
-                $IMAGE_NAME:latest
-                '
+                scp docker-compose.yaml ubuntu@3.108.42.35:/home/ubuntu/
+                ssh ubuntu@3.108.42.35'''
+                cd /home/ubuntu
+                docker-compose down
+                docker-compose up -d
+                '''
                 """
             }
-        }
-    }
-    post {
-        success {
-            echo "Deployment successful"
-        }
-        failure {
-            echo "Deployment failed"
         }
     }
 }
