Letest Modified

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,34 +1,73 @@
-pipeline {
-    agent {label 'frontend'}
+pipeline{
+    agent any
     environment {
-
-        APP_SERVER = "172.31.36.61"
-        DEPLOY_DIR = "/var/www/html"
+        IMAGE_NAME = "ajaydhadi95/frontend"
+        IMAGE_TAG = "${BUILD_NUMBER}"
+        APP_SERVER = "15.206.149.108"
     }
     stages {
-        stage('pre build actions'){
-            steps{
-                sh 'npm install'
-                
+        stage('checkout') {
+            steps {
+                git branch: 'main',
+                url: 'https://github.com/ajaydhadi95-gif/Jenkins-webapp.git'
             }
         }
-         stage('build'){
-             steps{
-                 sh 'npm run build'
+        stage('build Docker image'){
+            steps {
+                sh '''
+                docker build  -f docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
+                '''
             }
         }
-        stage('post build actions'){
-             steps{
-                 
-                 sh """
-                 echo 'cleaning old files on app server'
-                 ssh jenkins@${APP_SERVER} 'rm -rf ${DEPLOY_DIR}/*'
-                 echo 'copying frontend build'
-                 scp -r dist/* jenkins@${APP_SERVER}:${DEPLOY_DIR}/
-                 ssh jenkins@${APP_SERVER} 'sudo systemctl restart nginx'
-                 
-                 """
+        stage('Docker Login') {
+            steps {
+                withCredentials([
+                    usernamePassword(
+                        CredentialsID: 'DockerCred',
+                        usernameVariable: 'DOCKER_USER',
+                        passwordVariable: 'DOCKER_PASS',
+                    )
+                ]) {
+                    sh'''
+                    echo $DOCKER_PASS | docker login \
+                    -u $DOCKER_USER \
+                    --password-stdin
+                    '''
+                }
             }
+        }
+        stage('push Image') {
+            steps {
+                sh '''
+                docker push $IMAGE_NAME:IMAGE_TAG
+                docker tag \
+                $IMAGE_NAME:latest
+                docker push $IMAGE_NAME:latest
+                '''
+            }
+        }
+        stage('Deploy to App Server') {
+            steps {
+                sh """
+                ssh ubuntu@$APP_SERVER '
+                docker pull $IMAGE_NAME:latest
+                docker stop frontend || true
+                docker rm frontend || true
+                docker run -d \
+                --name frontend \
+                -p 80:80 \
+                $IMAGE_NAME:latest
+                '
+                """
+            }
+        }
+    }
+    post {
+        success {
+            echo "Deployment successful"
+        }
+        failure {
+            echo "Deployment failed"
         }
     }
 }
