Letest Modified jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,89 +1,165 @@
+// // pipeline{
+// //     agent any
+// //     environment {
+// //         IMAGE_NAME = "ajaydhadi95/frontend"
+// //         IMAGE_TAG = "${BUILD_NUMBER}"
+// //         APP_SERVER = "15.206.149.108"
+// //     }
+// //     stages {
+// //         stage('checkout') {
+// //             steps {
+// //                 git branch: 'main',
+// //                 url: 'https://github.com/ajaydhadi95-gif/Jenkins-webapp.git'
+// //             }
+// //         }
+// //         stage('build Docker image'){
+// //             steps {
+// //                 sh '''
+// //                 docker build  -f docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
+// //                 '''
+// //             }
+// //         }
+// //         stage('Docker Login') {
+// //             steps {
+// //                 withCredentials([
+// //                     usernamePassword(
+// //                         credentialsId:'DockerCred',
+// //                         usernameVariable:'DOCKER_USER',
+// //                         passwordVariable:'DOCKER_PASS',
+// //                     )
+// //                 ]) {
+// //                     sh'''
+// //                     echo $DOCKER_PASS | docker login \
+// //                     -u $DOCKER_USER \
+// //                     --password-stdin
+// //                     '''
+// //                 }
+// //             }
+// //         }
+// //         stage('push Image') {
+// //             steps {
+// //                 sh '''
+// //                 docker push $IMAGE_NAME:$IMAGE_TAG
+// //                 docker tag \
+// //                 $IMAGE_NAME:$IMAGE_TAG \
+// //                 $IMAGE_NAME:latest 
+// //                 docker push $IMAGE_NAME:latest
+// //                 '''
+// //             }
+// //         }
+// //         stage('Deploy to App Server') {
+// //             steps {
+// //                 sh """
+// //                 ssh ubuntu@$APP_SERVER '
+// //                 docker pull $IMAGE_NAME:latest
+// //                 docker stop frontend || true
+// //                 docker rm frontend || true
+// //                 docker run -d \
+// //                 --name frontend \
+// //                 -p 80:80 \
+// //                 $IMAGE_NAME:latest
+// //                 '
+// //                 """
+// //             }
+// //         }
+// //     }
+// //     post {
+// //         success {
+// //             echo "Deployment successful"
+// //         }
+// //         failure {
+// //             echo "Deployment failed"
+// //         }
+// //     }
+// // }
+
+
 // pipeline{
 //     agent any
-//     environment {
-//         IMAGE_NAME = "ajaydhadi95/frontend"
-//         IMAGE_TAG = "${BUILD_NUMBER}"
-//         APP_SERVER = "15.206.149.108"
-//     }
-//     stages {
-//         stage('checkout') {
-//             steps {
-//                 git branch: 'main',
-//                 url: 'https://github.com/ajaydhadi95-gif/Jenkins-webapp.git'
-//             }
-//         }
-//         stage('build Docker image'){
-//             steps {
-//                 sh '''
-//                 docker build  -f docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
-//                 '''
-//             }
-//         }
-//         stage('Docker Login') {
-//             steps {
-//                 withCredentials([
-//                     usernamePassword(
-//                         credentialsId:'DockerCred',
-//                         usernameVariable:'DOCKER_USER',
-//                         passwordVariable:'DOCKER_PASS',
-//                     )
-//                 ]) {
-//                     sh'''
-//                     echo $DOCKER_PASS | docker login \
-//                     -u $DOCKER_USER \
-//                     --password-stdin
-//                     '''
-//                 }
-//             }
-//         }
-//         stage('push Image') {
-//             steps {
-//                 sh '''
-//                 docker push $IMAGE_NAME:$IMAGE_TAG
-//                 docker tag \
-//                 $IMAGE_NAME:$IMAGE_TAG \
-//                 $IMAGE_NAME:latest 
-//                 docker push $IMAGE_NAME:latest
-//                 '''
-//             }
-//         }
-//         stage('Deploy to App Server') {
-//             steps {
+//     stages{
+//         stage('Deployment'){
+//             steps{
 //                 sh """
-//                 ssh ubuntu@$APP_SERVER '
-//                 docker pull $IMAGE_NAME:latest
-//                 docker stop frontend || true
-//                 docker rm frontend || true
-//                 docker run -d \
-//                 --name frontend \
-//                 -p 80:80 \
-//                 $IMAGE_NAME:latest
-//                 '
+//                 scp docker-compose.yaml ubuntu@3.108.42.35:/home/ubuntu/
+//                 ssh ubuntu@3.108.42.35 "cd /home/ubuntu && docker-compose down && docker-compose up -d"              
 //                 """
 //             }
 //         }
 //     }
-//     post {
-//         success {
-//             echo "Deployment successful"
-//         }
-//         failure {
-//             echo "Deployment failed"
-//         }
-//     }
 // }
-
 
 pipeline{
     agent any
+    environment{
+        AWS_REGION = 'ap-south-1'
+        ACCOUNT_ID = '174376948569'
+        REPOSITORY = 'frontend'
+        IMAGE_TAG = '${BUILD_NUMBER}'
+        ECR_URI = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPOSITORY}:${IMAGE_TAG}"
+        ACCESS_KEY_ID = credentials('ACCESS_KEY_ID')
+        SECRET_ACCESS_KEY = credentials('SECRET_ACCESS_KEY')
+        CLUSTER_NAME = 'default'
+        SERVICE_NAME = 'frontend-f2ec'
+
+
+    }
     stages{
-        stage('Deployment'){
+        stage('Checkout'){
+            steps{
+                checkout scm
+            }
+        }
+        stage('Build Docker Image'){
             steps{
                 sh """
-                scp docker-compose.yaml ubuntu@3.108.42.35:/home/ubuntu/
-                ssh ubuntu@3.108.42.35 "cd /home/ubuntu && docker-compose down && docker-compose up -d"              
+                docker build  -f docker/dockerfile -t ${REPOSITORY}:${IMAGE_TAG} .
                 """
             }
+        }
+        stage('Login to AWS ECR'){
+            steps{
+                sh """
+                aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
+                """
+            }
+        }
+        stage ('Login to AWS CLI'){
+            steps{
+                sh """
+                aws configure set aws_access_key_id ${ACCESS_KEY_ID}
+                aws configure set aws_secret_access_key ${SECRET_ACCESS_KEY}
+                aws configure set default.region ${AWS_REGION}
+                """
+            }
+        }
+        stage('Tag and Push Docker Image to ECR'){
+            steps{
+                sh """
+                docker tag ${REPOSITORY}:${IMAGE_TAG} ${ECR_URI}
+                docker push ${ECR_URI}
+                """
+            }
+        }
+        stage('Deploy to ECS Service'){
+            steps{
+                sh """
+                aws ecs update-service \
+                --cluster ${CLUSTER_NAME} \
+                --service ${SERVICE_NAME} \
+                --force-new-deployment
+                """
+            }
+        }
+    }
+    post{
+        success{
+            echo "Deployment Successful!"
+            cleanWs()
+            sh 'docker image prune -f'
+        }
+        failure{
+            echo "Deployment Failed!"
+            cleanWs()
         }
     }
 }
